#! /usr/bin/python

"""
This is a strace analyser script

One should use it like this:

strace -f -ttt -v -qq -T -s 1024 -p <pid> 2>&1 | strace-analyser
"""

import fileinput
import logging.config
import pkg_resources
import yaml
from strace_analyser import StraceProcessor, SysCallAnalyser


def main():
    """ The main entry point """
    conf_file = pkg_resources.resource_filename('strace_analyser',
                                                'strace-analyser.yaml')
    conf = yaml.load(open(conf_file))
    logging.config.dictConfig(conf['logging'])

    processor = StraceProcessor()
    analyser = SysCallAnalyser(conf['syscalls']['ignore'])
    for line in fileinput.input():
        evt = processor.process(line)
        analyser.process(evt)

if __name__ == '__main__':
    main()
